# S07E03 - Modules & CRUD

## Menu du jour

```
### Matin ###

- Correction atelier
  - FETCH : gestion d'erreur
  - POST : body format / body parser

- Découpage en modules 
  - Multiple scripts import
  - ESM and "module" scripts
  - `vite` (si le temps le permet)

### Après-midi ###

- CRUD sur le front : 
  - on continue le projet !

```

## Git flow

- `git checkout master`
- `git fetch prof`
- `git reset --hard prof/master`


### Gestion des erreurs lors d'un `fetch`

On commence à coder au plus simple :
on fait en sorte que ça marche !

Ensuite, on va chercher à gérer les erreurs ;
erreurs possibles :

- le serveur n'est pas lancé
- erreur 500 (mauvaise configuration du serveur)
- erreur 404 (mauvaise route)
- erreur 400 (mauvaise requête)

#### Le serveur n'est pas lancé

> Erreur `ERR_CONNECTION_REFUSED` (Chrome)  
> `(Reason: CORS request did not succeed). Status code: (null).` (FF)
>
> → le serveur n'est pas lancé

Solution :
on vérifie ses accès (`.env`) et on (re)lance le serveur…

Côté front, on ne récupère pas de `response` précise dans le 1er cas…

On met en place un `try/catch`

```js
try {
  const response = await fetch(`${API_BASE_URL}/lists`);
  console.log(response);

  const lists = await response.json();

  lists.forEach((list) => {
    addList(list);
  });
} catch (error) {
  console.error(error);

  const msg = `
    Le serveur ne répond pas. Merci de ré-essayer ultérieurement.
    [Error message: ${error.message}]
  `;
  alert(msg);
}
```

#### Erreurs côté serveur
>
> Erreur 500 `INTERNAL SERVER ERROR`  
> → mauvaise BDD, mauvais nom d'utilisateur…

Cette fois-ci on a une réponse de l'API…

Le `console.log(response)` renvoie une erreur avec un statut
retourné par l'API (notre `errorController._500`).

Pour lire le message associé à l'erreur : on fait un `console.log`
de la réponse lue et convertie en objet (`await response.json()`).

> **RAPPEL** pour la sécurité, il faut modifier le message reçu
> par les erreurs 500 pour éviter d'en dire trop…

MAIS il se passe quelque chose d'important :
**l'erreur affichée en console n'est pas l'erreur du fetch** !!!  

Elle est due au `forEach` qui n'est pas une fonction d'objet…  
On commente pour voir : on a plus l'erreur en console.

En fait, JS (et le `try/catch`) considère que de recevoir
une **erreur 500 n'est pas une erreur mais une réponse**.  
Aucune raison d'aller dans le `catch` à ce niveau-là.

On va donc vouloir forcer l'erreur…

Dans la réponse, il y a toutefois un indice pour savoir
si la réponse est de type plutôt succès ou plus erreur :

```js
{
  // ...
  ok: false,
  status: 500,
  statusText: 'Internal Server Error',
}
```

Pour forcer une erreur, on va en déclencher une manuellement,
quand `response.ok` vaut `false`.

```js
if (!response.ok) {
  // je déclenche une erreur manuelle, qui sera capturée par le `catch`
  throw new Error('Problème de connexion');
}
```

#### Erreurs côté client

##### Erreur 404

La route n'est pas trouvée  
→ on vérifie bien l'URL, c'est sans doute une coquille

##### Erreur 400

La requête envoyée n'est pas dans le format attendu.

On a codé notre API en fonction d'attentes, surtout pour
les requêtes envoyées avec un `body` :
il faut les bonnes informations dans le bon format.

Exemple : on soumet le formulaire sans renseigner de nom de liste…

De la même manière, on peut déclencher une erreur manuellement…

